---

- hosts: zabbix_clients
  become: yes

  ## Add your date
  vars:
    zabbix_server_ip: ""
    repo_inst: "false"
    port_enable: "false"

  tasks:

  ##### Add Ubuntu repo #####
  - import_tasks: zabbix_ubuntu_repo.yml
    when: ansible_distribution == "Ubuntu" and repo_inst == "true"
  - debug:
      msg: "DEB repository is installed"
    when: ansible_distribution == "Ubuntu" 

  ##### Add CentOS repo #####
  - import_tasks: zabbix_centos_repo.yml
    when: ansible_distribution == "CentOS" and repo_inst == "true"
  - debug:
      msg: "RPM repository is installed"
    when: ansible_distribution == "CentOS" 

  ##### Install zabbix-agent for Ubuntu #####
  - name: Install zabbix-agent (Ubuntu)
    apt:
      name: zabbix-agent
      state: present
    when: ansible_distribution == "Ubuntu"

  ##### Install zabbix-agent for CentOS #####
  - name: Install zabbix-agent (CentOS)
    yum:
      name: zabbix-agent
      state: present
    when: ansible_distribution == "CentOS"
  
    ##### Configure /etc/zabbix/zabbix_agentd.conf #####
  
  - name: Wait config file /etc/zabbix/zabbix_agentd.conf
    wait_for:
      path: /etc/zabbix/zabbix_agentd.conf

  - name: Change Server
    replace:
      path: "/etc/zabbix/zabbix_agentd.conf"
      regexp: '^Server=(.*)$'
      replace: 'Server={{zabbix_server_ip}}'

  - name: Change Hostname
    replace:
      path: "/etc/zabbix/zabbix_agentd.conf"
      regexp: '^Hostname=(.*)$'
      replace: 'Hostname={{ansible_hostname}}'

  - name: Install UserParameter test
    template:
      src: /etc/ansible/common/files/zabbix_test.conf
      dest: /etc/zabbix/zabbix_agentd.d/zabbix_test.conf

  ##### Restart and Enable service
  - name: Systemd
    systemd:
      name: zabbix-agent
      state: restarted
      enabled: yes

  ##### Open port 10050 #####
  - import_tasks: open.10050.port.yml
    when: port_enable == "true"
  - debug:
      msg: "Port 10050 is opened"

